//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int payment_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_method { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual orders orders { get; set; }
    }
}
