//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sostav_bluda
    {
        public int id_sostav { get; set; }
        public Nullable<int> bludo_id { get; set; }
        public Nullable<int> produck_id { get; set; }
        public Nullable<int> ves { get; set; }
    
        public virtual bludo bludo { get; set; }
        public virtual products products { get; set; }
    }
}
