//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_products
    {
        public int supply_id { get; set; }
        public int product_id { get; set; }
        public int postavki_id { get; set; }
        public Nullable<int> kolichestvo { get; set; }
    
        public virtual products products { get; set; }
        public virtual supplies supplies { get; set; }
    }
}
